=== brabenetz/settings4j/settings4j/trunk/src/main/resources/org/settings4j/config/settings4j.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<!-- Authors: Chris Taylor, Ceki Gulcu. -->

<!-- Version: 1.2 -->

<!-- A configuration element consists of optional renderer
elements,appender elements, categories and an optional root
element. -->

<!ELEMENT settings4j:configuration (connector*,settings*,root?,
                               contentResolver*, objectResolver*)>

<!ATTLIST settings4j:configuration
  xmlns:settings4j              CDATA #FIXED "http://settings4j.org/"
>

<!-- Appenders must have a name and a class. -->
<!-- Appenders may contain an error handler, a layout, optional parameters -->
<!-- and filters. They may also reference (or include) other appenders. -->
<!ELEMENT connector (param*, connectionSource?,
      contentResolver-ref*, objectResolver-ref*, connector-ref*)>
<!ATTLIST connector
  name 		CDATA 	#REQUIRED
  class 	CDATA	#REQUIRED
>

<!ELEMENT settings-ref EMPTY>
<!ATTLIST settings-ref
  ref CDATA #REQUIRED
>

<!ELEMENT connector-ref EMPTY>
<!ATTLIST connector-ref
  ref CDATA #REQUIRED
  readonly (true|false) "false"
>

<!ELEMENT contentResolver-ref EMPTY>
<!ATTLIST contentResolver-ref
  ref CDATA #REQUIRED
>

<!ELEMENT objectResolver-ref EMPTY>
<!ATTLIST objectResolver-ref
  ref CDATA #REQUIRED
>

<!ELEMENT param EMPTY>
<!ATTLIST param
  name		CDATA   #REQUIRED
  value		CDATA	#REQUIRED
>

<!-- If no level element is specified, then the configurator MUST not -->
<!-- touch the level of the named logger. -->
<!ELEMENT settings (param*,connector-ref*)>
<!ATTLIST settings
  factoryClass         CDATA   #IMPLIED
  name		CDATA	#REQUIRED
  additivity	(true|false) "true"  
>

<!ELEMENT contentResolver (param*, contentResolver-ref*)>
<!ATTLIST contentResolver
  name 		CDATA 	#REQUIRED
  class 	CDATA	#REQUIRED
>

<!ELEMENT objectResolver (param*, objectResolver-ref*)>
<!ATTLIST connector
  name 		CDATA 	#REQUIRED
  class 	CDATA	#REQUIRED
>

<!ELEMENT connectionSource (dataSource?, param*)>
<!ATTLIST connectionSource
  class        CDATA  #REQUIRED
>

<!ELEMENT dataSource (param*)>
<!ATTLIST dataSource
  class        CDATA  #REQUIRED
>


<!-- If no priority element is specified, then the configurator MUST not -->
<!-- touch the priority of root. -->
<!-- The root category always exists and cannot be subclassed. -->
<!ELEMENT root (param*, connector-ref*)>

=== brabenetz/settings4j/settings4j/tags/settings4j-1.0-beta3/src/test/resources/org/settings4j/connector/db/testHibernateDBConnector1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE settings4j:configuration SYSTEM "http://settings4j.org/archiv/1.0.0-beta-SNAPSHOT/XMLSchema/settings4j.dtd">
<!--
	Licensed to the Apache Software Foundation (ASF) under one or more
	contributor license agreements.  See the NOTICE file distributed with
	this work for additional information regarding copyright ownership.
	The ASF licenses this file to You under the Apache License, Version 2.0
	(the "License"); you may not use this file except in compliance with
	the License.  You may obtain a copy of the License at
	
	http://www.apache.org/licenses/LICENSE-2.0
	
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
-->

<settings4j:configuration xmlns:settings4j='http://settings4j.org/'>

	<connector name="HibernateDBConnector"
		class="org.settings4j.connector.db.HibernateDBConnector">
		<param name="hibernateConfigXmlKeys" value="org/settings4j/hibernate.cfg.xml" />
		<contentResolver-ref ref="DefaultContentResolver" />
		<objectResolver-ref ref="DefaultObjectResolver" />
	</connector>
	
	<connector name="SystemPropertyConnector"
		class="org.settings4j.connector.SystemPropertyConnector">
		<contentResolver-ref ref="DefaultContentResolver" />
		<objectResolver-ref ref="DefaultObjectResolver" />
	</connector>
	
	<connector name="ClasspathConnector" class="org.settings4j.connector.ClasspathConnector" >
		<objectResolver-ref ref="DefaultObjectResolver" />
	</connector>

	<contentResolver name="DefaultContentResolver" class="org.settings4j.contentresolver.UnionContentResolver">
		<contentResolver-ref ref="FSContentResolver" />
		<contentResolver-ref ref="ClasspathContentResolver" />
	</contentResolver>

	<contentResolver name="FSContentResolver"
		class="org.settings4j.contentresolver.FSContentResolver">
	</contentResolver>

	<contentResolver name="ClasspathContentResolver"
		class="org.settings4j.contentresolver.ClasspathContentResolver">
	</contentResolver>

	<objectResolver name="DefaultObjectResolver" class="org.settings4j.objectresolver.UnionObjectResolver">
		<objectResolver-ref ref="JavaXMLBeansObjectResolver" />
		<objectResolver-ref ref="SpringConfigObjectResolver" />
	</objectResolver>
	
	<objectResolver name="JavaXMLBeansObjectResolver" class="org.settings4j.objectresolver.JavaXMLBeansObjectResolver">
	</objectResolver>
	
	<objectResolver name="SpringConfigObjectResolver" class="org.settings4j.objectresolver.SpringConfigObjectResolver">
	</objectResolver>
	
</settings4j:configuration>
